### ISSUE TITLE
Install Script for Coming Soon Master

### ISSUE THREAD

**Issue by tech-prodigy** [tech-prodigy/coming-soon-master#1]
Hi,

We need to make sure that the install script is creating tables for the user in the database if those tables don't exists.

Also make sure that the default entries are being added to them so that the data is being inserted into these tables.

The following tables should be there :

1) Main Table for Parent Records
2) Meta Table for Child Records
3) Licensing Table

**Comment by tech-prodigy1** [comment]
Changes in install script.
