### ISSUE TITLE
Logo Settings of the Layout settings Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#10]
Hi Manpreet,

Here are the tasks for you for the Logo Settings of the Layout settings Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
• Remove mandatory mark(*) from Custom CSS field.
• Validate the fields marked with a star.
•       Upload button should work properly for uploading an image(using  wp media  uploader). 
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy11** [comment]
Bug ID/Issue ID: #10 Changes Made at  5:51PM

# Changed Files: 
1. views\layout-settings\logo-settings\logo-settings.php
2. includes\footer.php
3. lib\action-library.php
4. lib\sidebar-menu.php

# Issues Fixed:
1. Uploder in Logo Settings Page.
2. Selected Color in Color Picker By Value in The Textbox.
3. Change Key of Custom Css Textarea custom_css_logo_settings_layout in Logo Settings.
4. Change in Toaster Message "Logo Settings has been Saved Successfully.".
5. Replace Color picker js file .
6. stripslashes,htmlspecialchars_decode,urldecode in required fields in Logo Settings .
7. Declare $wp-version variable in csm_logo_settings function .
8. Add stripslashes,htmlspecialchars_decode,urldecode For Selecting Font Style in footer.php .
9. Validate_Digits function for only digits in required textbox

Note: Yet Files are not checked in.

# Changed By : 

Manpreet Singh

**Comment by tech-prodigy11** [comment]
Bug ID/Issue ID: #10 Changes Made at  5:51PM

# Changed Files: 
1. views\layout-settings\logo-settings\logo-settings.php
2. includes\footer.php
3. lib\action-library.php

# Issues Fixed:
1. check_color function for only color picker.
2. encodeURIComponent for textbox in footer.
3. urldecode,stripslashes in action library for logo_settings_module function
4. trim,htmlspecialchars,htmlspecialchars_decode in logo settings

# Changed By : 

Manpreet Singh

**Comment by tech-prodigy11** [comment]
All issues are fixed.
