### ISSUE TITLE
Background Settings Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#12]
Hi Shilpa,
Here are the tasks for you for the Background Settings Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Validate the fields marked with a star and remove mandatory marks(*) from the custom css field.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Use Pluploader for uploading images.
• Use default backgrounds for the "Choose background" field.
• Use default Slide shows for the "Choose Slide Show" field.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Changed Files:

includes/footer.php
lib/action-library.php
views/background-settings/background-settings.php
assets/admin/layout/css/custom.css

Issues Fixed:

Validations are given on text fields.

All the default values of the meta tables has been updated successfully.

Loader and toaster notifications are working properly.

Images are uploaded properly.

Roles and capabilities along with wp-nonces/

Changed By:

Shilpa

**Comment by tech-prodigy7** [comment]
Issue ID: #12 changes made at 5:55 PM 

Changed Files: 
1. views\background-settings\background-settings.php
2. includes\footer.php
3. assets\admin\layout\css\custom.css
4. lib\action-liberary.php

Issues Fixed:
1. Validations are given on text fields.
2. Default settings of meta table are display on the screen in respective columns.
3. Loader and toaster notifications are working properly.
4. The meta tables has been updated successfully.
5. Nonces created
6. Default color are set in color textbox.
7. Value less than one enter in color opacity textbox.
8. All the fields are sanitized properly.
9. Images are uploaded properly.

Note: All issues are not fixed so this ticket is not marked as closed.

Tested By : Sonal 

Changed By : Shilpa Rana

**Comment by tech-prodigy7** [comment]
Closed #12
