### ISSUE TITLE
Error Settings of the Subscription Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#15]
Hi Sonali,

Here are the tasks for you for the Error Settings of the Subscription Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
• Remove mandatory mark(*) from Custom CSS field.
• Validate the fields marked with a star.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy10** [comment]
Issue ID: #15 Changes Made at  4:25PM

# Changed Files: 
1. subscription\error-settings.php
2. lib\action-library.php
3. includes\footer.php

# Issues Fixed:
1. Naming Conventions
2. Nonces created
3. stripslashes(htmlspecialchars_decode(urldecode($meta_data_array["error_text_subscription"]))) Changed in error text
4. jQuery in ready function
5. submitHandler
6. case "subscription_error_settings_module" : Created for updation.
7. Toster Notification in footer.php

Note: Reported Issues are fixed. so this ticket has been marked as closed.

# Changed By :

Sonali Sharma

**Comment by tech-prodigy10** [comment]
Issue ID: #15 Changes Made at 5:50PM

# Changed Files: 
1. subscription\error-settings.php
2. includes\footer.php

# Issues Fixed:
1. Only digits show in margin and padding.

Note: Yet Files are not checked in.

# Changed By :

Sonali Sharma
