### ISSUE TITLE
Button Settings of the Subscription Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#18]
Hi Shivani,

Here are the tasks for you for the Button Settings of the Subscription Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
• Remove mandatory mark(*) from Custom CSS field.
• Validate the fields marked with a star.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy13** [comment]
Changed Files:

```
includes/footer.php
lib/action-library.php
```

views/buttons-settings.php
    views/contact-form/button-settings/google-map-settings.php

Issues Fixed:

```
Validations are given on text fields.
All the default addresses of the meta tables has been updated successfully.

Loader and toaster notifications are working properly.

Note: pending issue font style
```

Changed By:

Shivani jangta

**Comment by tech-prodigy13** [comment]
Issue ID: #18 Changes made at 5:50 PM

Changed Files:

```
1. includes/footer.php
2. lib/action-library.php
3. views/subscription/button-settings/button-settings.php
```

Issues Fixed:

```
1. Validations are given on text fields.
2. All the default addresses of the meta tables has been updated successfully.
3. Loader and toaster notifications are working properly.
4. The problem of Font Style updating has been solved.
5. The button settings page properly reads all the default settings from the meta table and displays on the screen in respective columns.
6. ColorPicker is working properly.
7. Mandatory mark(*) is removed from Custom CSS field.
8. All the fields are sanitized properly and updated in the database.
```

Note: Reported issues are fixed.So this issue is marked as closed.
Tested By: Priyanka 

Changed By:
Shivani Jangta

#
