### ISSUE TITLE
 Social Media Settings Screen

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#2]
Hi Shiffi,

Here are the tasks for you for the Social Media Settings Page/Screen.
- Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
- Validate the fields marked with a star.
- Please make sure that the page properly updates all the default settings to the meta tables.
- Toster Notification should be shown when an update button is being clicked.
- Loader Works properly and refreshes the page after the update.
- Please make sure that all the fields are being sanitized properly before updating them to the database.
- Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards

Priyanka S.
Team Leader

**Comment by tech-prodigy5** [comment]
I have completed the task and committed the code.

**Comment by tech-prodigy2** [comment]
Validations are not working properly.

**Comment by tech-prodigy5** [comment]
Reported issues are fixed and files are checked in. So this issue is marked as closed.

**Comment by tech-prodigy5** [comment]
# Issues Fixed:
1. fixed Syntax Issues
   2.Change the Notification message

# Changed Files:

1.footer.php

**Comment by tech-prodigy5** [comment]
This reported issues are fixed. So this bug marking as closed.
