### ISSUE TITLE
General Settings Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#27]
Hi Nancy,
Here are the tasks for you for the General Settings Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when save settings buttton is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal

**Comment by tech-prodigy9** [comment]
Closed #27
