### ISSUE TITLE
Adding new menus

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#28]
Hi Shilpa,
Here are the tasks for you-
• Please add three new menus in our plugin.
a) Language Strings - Add this menu just after Plugin Mode.
b) Subscriber - Add this menu just after  Subscription.
c) Contact Form Data - Add this menu just after Contact Form.
• Please make sure that all the above pages are properly mentioned in all the three files - 1) sidebar-menu.php 2) sidebar.php 3) footer.php.
• Use Bulk-Delete dropdown with values Bulk-delete and Export and an Apply button in both files Subscriber and Contact Form Data .
• Use oTable for pagination in both files Subscriber and Contact Form Data.
• Columns for Subscriber are E-mail Address,Date/Time,IP Address and Action.
• Columns for Contact Form Data are Name,E-mail,Message,Date/Time,IP Address and Action.
• Toster Notification should be shown when save settings buttton is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Issue ID:  #28 changes made at 11.00 AM 

Changed Files: 
1. lib\sidebar-menu.php
2. views\language-strings.php
3. views\contact-form-data.php
4. views\subscribers.php
5. includes\footer.php
6. includes\sidebar.php

Issues Fixed:
1. Three new menus are created in comin soon master.
   
     a). Language Strings
     b). Subscriber.
     c). Contact Form Data
2.  Bulk-Delete dropdown with values Bulk-delete and Export and an Apply button in both files Subscriber and Contact Form Data.
3. oTable for pagination in both files Subscriber and Contact Form Data.
4. E-mail Address,Date/Time,IP Address and Action are created in Subscribers.
5. Name,E-mail,Message,Date/Time,IP Address and Action in Contact Form Data.
6. Toater and Loader Works properly.
7. wp-nonces are created.

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Shilpa Rana

Tested By :  Sonal Wadhwa
