### ISSUE TITLE
 Plugin Mode Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#29]
Hello Shivani,

Here are the tasks for you for the Plugin Mode Page/Screen.

I.  Create a drop down list as Default Mode, it should be mandatory. This drop down will list out 3 values:
            1. Coming Soon Mode
            2. Maintenance mode
            3. Live website
II.      By default  "Live Website" should show in  "Default Mode" field.
III.     If 'Live Website" is selected in Default Mode field then below mentioned fields should  not show.  
II. Create a drop down list as Default Language, it should be mandatory. This drop down will contain multiple languages. default language should show 'English-US'
III.    Create a drop down list as Multi Site, it should be mandatory. This drop down will list out 2 values:
            1. Enable
            2. Disable
    Default Multi site should show 'Enable'
IV. If the user select Multi site as Enable then multi select box show below of the multi site drop down list.
        • User can Add Single or multiple languages from multi selection box using add button. Language should be listed in sorting order.
                • If user Remove added languages using Remove button. Languages should get added again back in sorted format. 
V.  Create a label as 'Theme'
VI. Create a submit button as 'Save Changes'
VII.    Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
VIII.   Validate the fields marked with a star.
IX. Please make sure that the page properly updates all the default settings to the meta tables.
X.  Toaster Notification should be shown when an update button is being clicked.
XI. Loader Works properly and refreshes the page after the update.
XII.    Please make sure that all the fields are being sanitized properly before updating them to the database.
XIII.   Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

**Comment by tech-prodigy2** [comment]
Shivani,

Please recheck your Issue detail.

**Comment by tech-prodigy3** [comment]
Issue ID: #29 Changes made at 1st-Aug-2015  3:30 PM

Changed Files:
1. includes/footer.php
2. includes/queries.php
3. lib/action-library.php
4. lib/install-script.php
5. views/plugin-mode/plugin-mode.php

Issues Fixed:

```
1. Drop down list is created with three default values.
2. Live Website is shown in default mode.
3. Drop down list is created  for Multi Site.
4. Enable is shown in Default Multi site.
5. Multi selection box  for multiple languages is created.
6. Languages are listed in sorting order.
7. Add and Remove button of multi select box is working properly.
8. Label is created as 'Theme'.
9. All the default addresses of the meta tables has been updated successfully.
10.Loader and toaster notifications are working properly.

 Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Shivani Jangta
```

   Tested By:
   Priyanka S.
