### ISSUE TITLE
Modify Install Script

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#3]
Hi Sonali,

There is a bug which has been notified into the Install Script.

It is being related to static urls.

Please make sure that no static url or path is being defined in any of the meta values in any of the tables. These should be dynamic in nature.

Also, please make sure that default email address and website url of the current website are stored against the email and website keys ins social media settings in meta table.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy10** [comment]
Bug ID: #3 Changes Made at  10:28AM

#   Changed Files: 
1. lib\install-script.php

# Issues Fixed:
1. Insert custom css
2. By Default Social Settings Should be blank
3. Image paths were Changed.
4. Values are changed for below mention fields:

formatted_address', 'Singapore'),
    (157, 20, 'area_zip_code', 'Singapore 247964'),
    (158, 20, 'latitude', '1.330256'),
    (159, 20, 'longitude', '103.906374')

Note: Reported Issues are fixed. so this ticket marking as a closed..

# Changed By :+1: 

Sonali Sharma

**Comment by tech-prodigy** [comment]
Please strictly follow naming conventions for custom css meta keys.

**Comment by tech-prodigy10** [comment]
Bug ID: #3 Changes Made at  11:02AM

 Naming Conventions for custom css meta keys are done.

Changed By:

Sonali Sharma
