### ISSUE TITLE
 Install script.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#30]
Hi Sonali

Here are the tasks for you for Install script.

• Please create two tables for subcription and contact form entries.
• Column structure:
        1. ID primary key int(10)
        2. Meta key varchar(100)
        3. Meta Value   text 
• Please make below mentioned entries on meta table:
        default-mode  live website
        default-language    en-us
        multisite       enable
        multi-site-language en_us,fr_fr,de_de
        theme           default

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy10** [comment]
closed #30
