### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#31]
Hi Nancy,

Here are the tasks for you-

• Please make sure that the all the folders of Coming-Soon-Master should be formatted properly.
• The Related Folders are - assets,lib,includes and views.
• Please make sure that the all the files under above mentioned folders should be formatted properly too.

Regards
Sonal
Team Leader

**Comment by tech-prodigy9** [comment]
closed #31
