### ISSUE TITLE
Subscribers Page/Screen and Contact-Form-Data Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#32]
Hi Nancy,

Here are the tasks for you for the Subscribers Page/Screen and Contact-Form-Data Page/Screen.

• In both pages, Manage all the data in  table.
• Firstly,insert an entry - type = "subscriber" and parent_id = "0" in main table of Coming-soon-Master.
• Insert second entry - type = "contact_entry" and parent_id = "0" in main table of Coming-soon-Master.
• Then,insert their related meta_keys and meta_values in meta table manually.
• Meta keys for "subscriber" are  email_address,date_time, IP_address and location.
• Meta keys for "contact_entry" are  name,email_address,message,date_time,IP_address and location.
• In both pages,use an icon icon-trash in Action column.
• Please make sure that the both pages properly read all the default settings from the meta table and displays on the screen in respective columns.
• Use encoded strings for the labels,so that it can accept string as well as special characters too.
• Toaster Notification should be shown when an delete icon is being clicked.
• Loader Works properly and refreshes the page after deletion.
• Please make sure that all the fields are being sanitized properly before update them to the database.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy9** [comment]
Issue ID: #32 Changes made at 10:55 AM

Changed Files:

```
1. includes/footer.php
2. includes/queries.php
3. lib/action-library.php
4. lib/helper.php
5. views/contact-form-data/contact-form-data.php
6. views/subscribers/subscribers.php
7. assets/admin/layout/css/custom.css
```

Issues Fixed:

```
1. Manage all the data from database.
2. Apply Bulk-Action And Delete function on both pages
3. Timestamp on date/time column
4. Start and End Date (Layout, On selected start and end date particular data has been shown)
5. In label setting page if we hide/show name_field, email_field, message_field corresponds to that in Contact Form Data page data from database will also 
```

changed.  

Note: Reported issues are fixed.So this issue is marked as closed.

Tested By:
Nancy Singla
