### ISSUE TITLE
Adding new menus and functionality

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#33]
Hi Nancy,

Here are the tasks for you for the new menus and some new functionality in existing menus-

• In Plugin mode Page/screen,according to first field Default Mode,by choosing "Coming Soon Mode" a button of Green color should be shown at the top of plugin in right side,by choosing "Maintenance Mode" a button of Red color should be shown at the top of plugin in right side and in case of Live Website no button should be shown.
• In Language Strings Page/screen,A drop down of selected languages should be there.The selected languages are from the Plugin Mode selected language field.
• A table with two Columns first column with any static string and second column with a textbox.
• Use o Table foe the above table.
• A Button named by Save Strings should be on the right side below this page.
• Add a new sub menu SEO settings in Layout Settings menu under Footer Settings sub menu,a text box with label Site Title,A text area with label Meta-description,A text area with label Meta-Keyword,A drop-down with label Meta Robots Follow and the options will be Follow and No Follow,a text box with label Canonical URL and a text area with label Tracking Code.
• A Button named by Save Settings should be on the right side below this page.
• Add a sub menu Email Templates In Contact form menu under Success Message settings same as captcha master but drop down values should be Template For Admin Notifications and Template For Client Notifications.
• Add a menu Email Management under Contact form menu same as Captcha Master.
• Please make sure that the all pages properly read all the default settings from the meta table and displays on the screen in respective columns.
• Use encoded strings for the labels,so that it can accept string as well as special characters too.
• Toaster Notification should be shown when an save button is being clicked.
• Loader Works properly and refreshes the page after deletion.
• Please make sure that all the fields are being sanitized properly before update them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy9** [comment]
Issue ID: #33 Changes made at 09:27 AM

Changed Files:

```
1. assets/admin/layout/css/custom.css
2. includes/footer.php
3. includes/queries.php
4. includes/sidebar.php
5. lib/install-script.php
6. lib/action-library.php
7. views/language-strings/language-strings.php
8. views/email-management/email-management.php
9. views/contact-form/email-templates/email-templates.php
10. views/contact-form/success-message-settings/success-message-settings.php
11. views/layout-settings/seo-settings/seo-settings.php
12. coming-soon-master.php
```

Issues Fixed:

```
1. Create layout of language-strings.php, seo-settings.php, email-templates.php, email-management.php
2. Update the values in database
3. Change the menu name of success-message-settings to message-settings.
4. Get the values of selected-language from plugin-mode.php to language-strings.php
5. In Plugin mode Page/screen,according to field default-mode,by choosing "Coming Soon Mode" a button of Green color should be shown at the top of plugin in right side,by choosing "Maintenance Mode" a button of Red color should be shown at the top of plugin in right side and in case of Live Website no button should be shown
6. Please make sure that the all pages properly read all the default settings from the meta table and displays on the screen in respective columns.
7. Use encoded strings for the labels,so that it can accept string as well as special characters too.
8. Toaster Notification should be shown when an save button is being clicked.
9. Loader Works properly and refreshes the page after deletion.
10. Please make sure that all the fields are being sanitized properly before update them to the database.
11. Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed
```

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Nancy Singla

Tested By:
Sonal Wadhwa
