### ISSUE TITLE
Sidebar Menus of Coming Soon Master

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#34]
Hi Nancy

Here are the tasks for you for Sidebar Menus of Coming Soon Master.

• Please make sure that the all the main menus of includes/sidebar.php will be shown in lib/sidebar-menus.php.
• After that,on sidebar menus.php file make a query to fetch all the data of plugin settings.php file from database on sidebar-menus.php.
• If Administrator is selected,then all the menus will be shown on sidebar of wordpress.
• But if any other is selected,no menu will be shown on sidebar of wordpress.

Regards
Sonal
Team Leader

**Comment by tech-prodigy9** [comment]
Issue ID: #34 Changes made at 03:55 PM

Changed Files:

```
1. lib/sidebar-menus.php
2. lib/admin-bar-menu.php
3. coming-soon-master.php
4. views/general-settings/general-settings.php
```

Issues Fixed:

```
1. Create Sub-Menus of coming soon master in main dashboard 
2. Create Sub-Menus of coming soon master in Top Bar Admin Menu 
3. When show_coming_soon_master_top_bar_menu is hide, top bar menu 
```

is also hide.

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Nancy Singla

Tested By:
Sonal Wadhwa
