### ISSUE TITLE
Countdown Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#5]
Hi Priya,
Here are the tasks for you for the Countdown Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Validate the fields marked with a star and remove mandotry mark(*) from the custom css field.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Use Datepicker for the date field.  
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy15** [comment]
Changed Files:

```
includes/footer.php
lib/action-library.php
views/countdown/countdown.php
assets/global/plugin/colorpicker/colpick.js
```

Issues Fixed:

```
Validations are given on text fields.
All the default addresses of the meta tables has been updated successfully.

Loader and toaster notifications are working properly.

Reported issues are fixed.So this issue is marked as closed.
```

Changed By:

priya

**Comment by tech-prodigy15** [comment]
Issue ID: #5 Changes made at 5:50 PM

Changed Files:
1. includes/footer.php
2. lib/action-library.php
3. lib/install-script.php
4. lib/sidebar-menu.php
5. views/countdown/countdown.php
6. include/sidebar.php
7. include/queries.php
   
   Issues Fixed:
8.  The  Countdown Page properly updates all the default settings to the meta tables.
9.  Loader and Toaster notifications are working properly.
10.  Validate_Digits function and Change Color function are created in footer.php file (Line No-143)
    and work properly.
11.  Gives <?php _e("",coming_soon_master)?> to each Time Zone Select Option on Countdown Page (Line No-172)
12.  Add stripslashes,htmlspecialchars_decode,urldecode For Selecting Font Family and Time Zone in 
    footer.php file (Line No-961,962)
13.  Add  trim,htmlspecialchars,htmlspecialchars_decode for Custom Css in countdown.php file (Line No-147)
14.  Change (67, 8, 'launch_time', '00,00,00'), into (67, 8, 'launch_time', '0,0,0'), and
    Change (70, 8, 'font_style_countdown', '20px,bold,#ccc'), into (70, 8, 'font_style_countdown', '20px,bold,#cccccc'),
    in install-script.php file (Line No-232,235)
15.  Validation done on field marked with *
    
    Note: Reported issues are fixed.So this issue is marked as closed.
    
    Tested By: Sonal Mam
    
    Changed By:
    
    Priya
