### ISSUE TITLE
Label Settings of Contact Form Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#6]
Hi Jaspreet,
Here are the tasks for you for the Label Settings of Contact Form Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Validate the fields marked with a star and remove mandatory mark(*) from the custom css field.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy12** [comment]
Changed Files:
    includes/footer.php
    lib/action-library.php
    views/contact-form/label-settings/label-settings.php

Issues Fixed:

```
Validations are given on text fields.
All the default addresses of the meta tables has been updated successfully.
slashes and the + sign is replaced with the white spaces and removed automativally when data retrieved from the database
Loader and toaster notifications are working properly.
```

Changed By:

Jaspreet Singh

**Comment by tech-prodigy12** [comment]
Changed Files:
    includes/footer.php
    lib/action-library.php
    views/contact-form/label-settings/label-settings.php

Issues Fixed:

```
Validations are given on text fields.
All the default addresses of the meta tables has been updated successfully.
slashes and the + sign is replaced with the white spaces and removed automatically when data retrieved from the database
Loader and toaster notifications are working properly.
```

   note: all issues are not fixed so this ticket is not marked as closed

Changed By:
Jaspreet Singh

**Comment by tech-prodigy12** [comment]
Issue ID: #6 Changes made at 05:55 AM

Changed Files:

```
includes/footer.php
lib/action-library.php
views/contact-form/label-settings/label_settings.php
```

Issues Fixed:

```
1.The Label_settings page updates all the default settings to the meta tables.

2.Colorpicker is working properly.

3.The Label_settings page properly reads all the default settings from the meta table and displays on the screen in respective              columns.

4.Mandatory mark(*) from Custom CSS field has been remove. 

5.Validations are working on fields marked with a star.

6.Toster Notification is shown when an update button is being clicked.

7.Loader Works properly and refreshes the page after the update.

8.All the fields have sanitized properly and updating to the database.
```

Note: Reported issues are fixed.So these issues are marked as closed.
Tested By : Sonal

Changed By:
Jaspreet Singh
