### ISSUE TITLE
Button Settings of Contact Form Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#7]
Hi Inderpreet,
Here are the tasks for you for the Button Settings of Contact Form Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Validate the fields marked with a star and remove \* from the custom css field.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy17** [comment]
Changed Files:

```
includes/footer.php
lib/action-library.php
views/contact-form/button-settings/button-settings.php
```

Issues Fixed:

```
Validations are given on text fields.
All the default addresses of the meta tables has been updated successfully.

Loader and toaster notifications are working properly.
Reported issues are fixed.So this issue is marked as closed.
```

Changed By:

Inderpreet

**Comment by tech-prodigy17** [comment]
Issue ID: #7 Changes Made at 5:51 PM

# Changed Files:

```
1. includes/footer.php
2. lib/action-library.php
3. views/contact-form/button-settings/button-settings.php
```

# Issues Fixed:

```
1. Validations are given on text fields.
2. All the default addresses of the meta tables has been updated successfully.
3. Loader and toaster notifications are working properly.
```

Note: Reported issues are fixed So this issue is marked as closed.
Tested By: Sonal

# Changed By:

Inderpreet
