### ISSUE TITLE
Success Messages Settings of Contact Form Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#9]
Hi Harpreet2,
Here are the tasks for you for the Success Messages Settings of Contact Form Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Validate the fields marked with a star and remove mandatory marks(*) from the custom css field.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy6** [comment]
# Issues Fixed:
1. fixed Syntax Issues
   2.Change the Notification message

# Changed Files:

1.footer.php

**Comment by tech-prodigy6** [comment]
Changed Files:

 1 includes/footer.php
 2 lib/action-library.php
 3 views/contact-form/contact-form/success-message-settings/success-message-settings.php

  Issues Fixed:
1. Page read all the default data from the database
2. Mandatory mark \* removed from custom css
3. Validation done on field marked with *
4. Page updates all values to meta table
5. Toster notification shown after click on save setting
6. Loader Works properly and refreshes the page after the update.
7. All the feilds are sanitized properly

changed by 
harpreet kaur

**Comment by tech-prodigy6** [comment]
Changed Files:

 1 includes/footer.php
 2 lib/action-library.php
 3 views/contact-form/contact-form/success-message-settings/success-message-settings.php

  Issues Fixed:
1. Page read all the default data from the database
2. Mandatory mark \* removed from custom css
3. Validation done on field marked with *
4. Page updates all values to meta table
5. Toster notification shown after click on save setting
6. Loader Works properly and refreshes the page after the update.
7. All the feilds are sanitized properly 
8. work properly in new wordpress

changed by 
harpreet kaur
